version: '3'

services:
  api:
    image: docker.pkg.github.com/appellation/meat/meat-api
    environment:
      CORS_ORIGIN: https://updog.wtf
    labels:
      - traefik.http.routers.api.rule=Host(`api.updog.wtf`)
      - traefik.http.routers.api.tls=true
  redis:
    volumes:
      - redis_data:/data
  reverse-proxy:
    ports:
      - 443:443
    volumes:
      - ./traefik/config.prod.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/certs:/etc/traefik/certs:ro
      - ./traefik/config:/etc/traefik/config:ro
    labels:
      - traefik.http.routers.dashboard.rule=Host(`dashboard.updog.wtf`)
      - traefik.http.routers.dashboard.tls=true
  site:
    image: docker.pkg.github.com/appellation/meat/meat-site
    labels:
      - traefik.http.routers.site.rule=Host(`updog.wtf`)
      - traefik.http.routers.site.tls=true

volumes:
  redis_data:
