version: '3'

services:
  api:
    environment:
      REDIS_URI: redis://redis
    restart: on-failure
    expose:
      - 8080
  redis:
    image: redis
    labels:
      - traefik.enable=false
  reverse-proxy:
    image: traefik:v2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  site:
    expose:
      - 3000
