version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    networks:
      - frontend
      - backend
    restart: on-failure
    environment:
      REDIS_URI: redis://redis:6379
      CORS_ORIGIN: https://updog.wtf
  redis:
    image: redis
    networks:
      - backend
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
  site:
    build:
      context: .
      dockerfile: ./site/Dockerfile
      args:
        - WS_API_BASE=wss://updog.wtf
        - HTTP_API_BASE=https://updog.wtf
    networks:
      - frontend

networks:
  frontend:
  backend:
