version: '3'

services:
  api:
    environment:
      REDIS_URI: redis://redis
    restart: on-failure
    expose:
      - 8080
  redis:
    image: redis
    labels:
      - traefik.enable=false
  reverse-proxy:
    image: traefik:v2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.http.routers.dashboard.entryPoints=dashboard
      - traefik.http.routers.dashboard.middlewares=dashboard-users
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.middlewares.dashboard-users.basicAuth.users=test:$$apr1$$g2f7XVCH$$P3EurA3sxLe3RYQHDCDvD0
  site:
    expose:
      - 3000
