env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - aqua/react
  - 'plugin:import/typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  # indent:
  #   - error
  #   - tab
  # no-tabs:
  #   - error
  #   - allowIndentationTabs: true

  # jsx-a11y/anchor-is-valid:
  #   - 'off'
  # jsx-a11y/label-has-associated-control:
  #   - error
  #   - controlComponents:
  #     - Input

  # import/extensions:
  #   - error
  #   - never

  comma-dangle:
    - error
    - functions: always-multiline

  react/jsx-filename-extension:
    - error
    - extensions:
      - .tsx
  react/react-in-jsx-scope:
    - 'off'

settings:
  import/extensions:
    - .tsx
    - .ts
