name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install pnpm
        run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm run -r build
